/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'val00362' at '16/05/26 16:15' with Gradle 2.9
 *
 * @author val00362, @date 16/05/26 16:15
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
