import org.junit.Test;

import javaTemplateGradle.JavaTemplateGradle;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'val00362' at '16/05/26 16:15' with Gradle 2.9
 *
 * @author val00362, @date 16/05/26 16:15
 */
public class JavaTemplateGradleTest {
    @Test public void testSomeLibraryMethod() {
        JavaTemplateGradle classUnderTest = new JavaTemplateGradle();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
